; Inno Setup Script for Bloom Operator Desktop App
; Use this script in Inno Setup Compiler on Windows to build a standard Setup.exe installer wizard.

[Setup]
AppName=Bloom Operator
AppVersion=1.0.0
AppPublisher=Bloomfield LLP
DefaultDirName={commonpf}\BloomOperator
DefaultGroupName=Bloom Operator
DisableProgramGroupPage=yes
OutputDir=dist
OutputBaseFilename=BloomOperatorSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Files]
; Copy all files generated by PyInstaller build
Source: "dist\BloomOperator\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
; Bundle the VC++ Redistributable installer
Source: "vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
; Create shortcuts in Start Menu and Desktop
Name: "{group}\Bloom Operator"; Filename: "{app}\BloomOperator.exe"
Name: "{commondesktop}\Bloom Operator"; Filename: "{app}\BloomOperator.exe"

[Run]
; Run VC++ Redistributable installer silently if not already installed
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; Check: VCNeedsInstall; StatusMsg: "Installing Microsoft Visual C++ Redistributable (x64)..."
; Option to launch application immediately after install completes
Filename: "{app}\BloomOperator.exe"; Description: "Launch Bloom Operator"; Flags: postinstall nowait skipifsilent

[Code]
function VCNeedsInstall: Boolean;
var
  Installed: Cardinal;
begin
  // RegQueryDWordValue returns True if value exists. Check for VS 2015-2022 x64 redistributable.
  if RegQueryDWordValue(HKEY_LOCAL_MACHINE, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Installed', Installed) then
  begin
    Result := (Installed <> 1);
  end
  else
  begin
    Result := True;
  end;
end;
