; Inno Setup Script for Bloom Operator Desktop App
; Use this script in Inno Setup Compiler on Windows to build a standard Setup.exe installer wizard.

[Setup]
AppName=Bloom Operator
AppVersion=1.0.0
AppPublisher=Bloomfield LLP
DefaultDirName={commonpf}\BloomOperator
DefaultGroupName=Bloom Operator
DisableProgramGroupPage=yes
OutputDir=dist
OutputBaseFilename=BloomOperatorSetup
Compression=lzma
SolidCompression=yes
SetupIconFile=static\images\loader-01.png
WizardStyle=modern

[Files]
; Copy all files generated by PyInstaller build
Source: "dist\BloomOperator\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
; Create shortcuts in Start Menu and Desktop
Name: "{group}\Bloom Operator"; Filename: "{app}\BloomOperator.exe"
Name: "{commondesktop}\Bloom Operator"; Filename: "{app}\BloomOperator.exe"

[Run]
; Option to launch application immediately after install completes
Filename: "{app}\BloomOperator.exe"; Description: "Launch Bloom Operator"; Flags: postinstall nowait skipifsilent
